Repository fusionjs/fusion-plugin-service-worker, pull requests merged in 2018-12, with the labels that each got.

#54 Fix types
  package.json
  src/__tests__/index.browser.js
  src/__tests__/index.node.js
  src/browser.js
  src/handlers.js
  src/mock-service-worker-source.js
  src/server.js
  src/types.js
  yarn.lock
Labels: bugfix

#56 Release v0.1.5-0
  package.json
Labels: release

#59 Remove @types/redux
  package.json
  yarn.lock
Labels: dependencies, refactor
