Repository fusionjs/fusion-plugin-service-worker, pull requests merged in 2019-02, with the labels that each got.

#90 Allow SW unregister across clients
  README.md
  src/__tests__/index.browser.js
  src/browser.js
  src/index.js
  src/tokens.js
  src/types.js
  src/utils.js
Labels: feature

#91 Release v1.1.0
  package.json
Labels: release

#92 Link to the Fusion Service Workers Guide
  README.md
Labels: bugfix, docs

#93 Release v1.1.1
  package.json
Labels: release

#98 Release v1.1.2-1
  package.json
Labels: release

#99 Support caching of CDN paths
  src/handlers.js
Labels: bugfix

#100 Release v1.1.2-2
  package.json
Labels: release

#101 Use correct path for CDNs
  src/handlers.js
Labels: bugfix

#102 Release v1.1.2-3
  package.json
Labels: release

#103 Release v1.1.2-3-debug
  package.json
Labels: release

#106 Release v1.1.2-3-debugging-1
  package.json
Labels: release

#110 Release v1.1.2-3-debugger-3
  package.json
Labels: release

#112 Release v1.1.2-4
  package.json
Labels: ci, release

#114 Use cache then update from network
  src/handlers.js
  src/server.js
Labels: feature

#115 Release v1.1.2-6
  package.json
Labels: release

#116 Upgrade fusion deps and fix flow regression
  package.json
  src/__tests__/index.node.js
  yarn.lock
Labels: bugfix

#117 Delete cache when we expected an html response but didn't get one
  src/handlers.js
  src/utils.js
Labels: bugfix

#118 Release v1.1.2-7
  package.json
Labels: release

#120 Release v1.2.0-0
  package.json
Labels: release

#119 Test first and second load Service Worker caching via puppeteer
  .dockerignore
  .eslintignore
  .flowconfig
  Dockerfile
  docker-compose.yml
  fixture-apps/app/flow-typed/globals.js
  fixture-apps/app/package.json
  fixture-apps/app/src/main.js
  fixture-apps/app/src/pages/home.js
  fixture-apps/app/src/pages/pageNotFound.js
  fixture-apps/app/src/root.js
  fixture-apps/app/src/sw.js
  package.json
  src/__tests__/fixtures/swTemplate.js
  src/__tests__/index.browser.js
  src/__tests__/index.node.js
  src/__tests__/utils.node.js
  yarn.lock
Labels: bugfix

#123 Remove circular dependency on itself
  package.json
Labels: bugfix

#124 Simplify test infrastructure
  .gitignore
  Dockerfile
  fixture-apps/app/flow-typed/globals.js
  fixture-apps/app/package.json
  fixture-apps/app/src/main.js
  package.json
  src/__tests__/utils.node.js
  yarn.lock
Labels: refactor

#125 Release v1.2.0-1
  package.json
Labels: release

#126 Release v1.2.0
  package.json
Labels: release

#127 Add tests for redirect, bad html, offline and response date checking
  fixture-apps/app/src/main.js
  fixture-apps/app/src/plugins/mock-redirect.js
  fixture-apps/app/src/plugins/mock-server-error.js
  fixture-apps/app/src/root.js
  src/__tests__/index.node.js
  src/handlers.js
Labels: bugfix

#128 Modularize tests
  src/__tests__/bad-response.node.js
  src/__tests__/happy-path.node.js
  src/__tests__/health.node.js
  src/__tests__/index.node.js
  src/__tests__/offline.node.js
  src/__tests__/redirect.node.js
  src/__tests__/utils.node.js
  src/handlers.js
Labels: refactor

#130 Release v1.3.0-0
  package.json
Labels: release

#131 Fix README code examples
  README.md
  src/index.js
Labels: bugfix

#132 Release v1.3.0-1
  package.json
Labels: release
