Repository fusionjs/fusion-plugin-service-worker, pull requests merged in 2019-01, with the labels that each got.

#66 Use template to generate sw.js
  README.md
  package.json
  src/browser.js
  src/index.js
  src/mock-service-worker-source.js
  src/server.js
  src/tokens.js
  yarn.lock
Labels: feature

#69 Release v0.3.0-0
  package.json
Labels: release

#72 Fix existing service worker test
  src/__tests__/fixtures/swTemplate.js
  src/__tests__/index.node.js
  src/browser.js
  src/server.js
Labels: bugfix

#73 Release v0.3.0-1
  package.json
Labels: release

#75 Release v1.0.0-0
  package.json
Labels: prerelease, release

#74 Release v1.0.0
  package.json
Labels: release

#79 Remove browser dependencies
  src/browser.js
Labels: bugfix

#81 Add README note for development
  README.md
Labels: bugfix, docs

#82 Migrate Flow to v0.91.0 and resolve errors
  package.json
  src/__tests__/fixtures/swTemplate.js
  src/types.js
  yarn.lock
Labels: bugfix

#83 Add tests and fix flow typing
  src/__tests__/fixtures/swTemplate.js
  src/__tests__/index.browser.js
  src/__tests__/index.node.js
  src/handlers.js
  src/types.js
Labels: bugfix

#84 Release v1.0.2
  package.json
Labels: release

#86 Fix lint
  src/__tests__/index.browser.js
  src/types.js
Labels: greenkeeping

#87 Add buildkite tasks
  .buildkite/browserTests
  .buildkite/nodeTests
  .buildkite/pipeline.yml
  Dockerfile
  docker-compose.yml
Labels: refactor

#88 Add logger token and more robust browser test
  README.md
  package.json
  src/__tests__/index.browser.js
  src/browser.js
  src/index.js
  src/tokens.js
  src/types.js
Labels: feature
