Repository fusionjs/fusion-plugin-service-worker, pull requests merged in 2019-03, with the labels that each got.

#134 Release v1.2.1-0
  package.json
Labels: release

#136 Release v1.3.1-debug
  package.json
Labels: release

#137 Release v1.3.0
  package.json
Labels: release

#141 Release v1.3.1-0
  package.json
Labels: release

#142 Release v1.3.1-1
  package.json
Labels: release

#145 Support regex matching for a) cache-busting resource names b) routes names that will bypass for network
  README.md
  docs/migrations/00145.md
  fixture-apps/app/src/main.js
  src/__tests__/bad-response.node.js
  src/__tests__/cache-busting-route-patterns.node.js
  src/__tests__/cache-expiry.node.js
  src/__tests__/cacheable-route-patterns.node.js
  src/__tests__/happy-path.node.js
  src/__tests__/health.node.js
  src/__tests__/index.browser.js
  src/__tests__/mulitple-routes.node.js
  src/__tests__/offline.node.js
  src/__tests__/redirect.node.js
  src/handlers.js
  src/index.js
  src/server.js
  src/tokens.js
  src/types.js
Labels: breaking

#146 Add `cacheDuration` name change
  docs/migrations/00145.md
Labels: docs

#147 Release v2.0.0-0
  package.json
Labels: release
